# Header Menu
menu:
  Home: /
rss: /atom.xml

# Integrations
email: uyeong21c@gmail.com
twitter: coderifleman
facebook: coderifleman
github: uyeong
disqus_shortname: coderifleman
google_analytics:

# Miscellaneous
title: Mooji
author: Coderifleman
description: frontend development stories.
version: 0.0.1
avatar:

# Environments
image_path: /assets/img
