# Header Menu
menu:
  Home: /
rss: /atom.xml

# Integrations
email: uyeong21c@gmail.com
twitter: coderifleman
facebook: coderifleman
github: uyeong
disqus_shortname: coderifleman
google_analytics: UA-55659240-1

# Environments
version: 0.0.1
image_path: /assets/img
